In [6]:
import numpy as np

In [1]:
cvalues = [20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 20.1]

fvalues = [((temp * 9) / 5 + 32) for temp in cvalues]
print(fvalues)

[68.18, 69.44, 71.42, 72.5, 72.86, 72.14, 71.24000000000001, 70.16, 69.62, 68.18]

A = np.array(list1)

In [9]:
A = np.array([[100, 50, 75, 89, 56, 30],
  [45, 75, 95, 90, 35, 100],
 [65, 78, 35, 24, 50, 60],
  [38, 30, 105, 57, 71, 93],
  [80, 60, 70, 65, 40, 80]])
count = (A > 50)
c = (True, count)
for i in count:
    print(np.sum(i))
print(np.sum(count, axis=0))

4
4
3
4
5
[3 3 4 4 2 4]

In [10]:
array = np.array([100, 50, 75, 89, 56, 30, 45,  75, 95, 90, 35, 100, 65,  78, 35, 24, 50, 60, 38,  30, 105, 57, 71, 93, 80, 60, 70, 65, 40, 80])
arr = np.reshape(array, (5,6))
emp_idx = (arr > 50)
num_emp_idx = (arr > 60)
print(np.sum(emp_idx, axis = 1))
print(np.sum(num_emp_idx, axis = 0))

[4 4 3 4 5]
[3 2 4 3 1 3]